version: '3'
services:
  promos-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/promos-app
    networks:
      - host

networks:
  host:
    driver: bridge